const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // 在循环外创建一次 test step，避免重复注册 panic
    const test_step = b.step("test", "Run all algorithm tests");

    // 每个算法文件注册为独立测试单元
    const test_files = [_][]const u8{
        // Sorts
        "sorts/bubble_sort.zig",
        "sorts/insertion_sort.zig",
        "sorts/merge_sort.zig",
        "sorts/quick_sort.zig",
        "sorts/heap_sort.zig",
        "sorts/radix_sort.zig",
        "sorts/bucket_sort.zig",
        "sorts/selection_sort.zig",
        "sorts/shell_sort.zig",
        "sorts/counting_sort.zig",
        "sorts/cocktail_shaker_sort.zig",
        "sorts/gnome_sort.zig",
        "sorts/binary_insertion_sort.zig",
        "sorts/bogo_sort.zig",
        "sorts/comb_sort.zig",
        "sorts/cycle_sort.zig",
        "sorts/double_sort.zig",
        "sorts/odd_even_sort.zig",
        "sorts/pancake_sort.zig",
        "sorts/recursive_insertion_sort.zig",
        "sorts/stooge_sort.zig",
        "sorts/wiggle_sort.zig",
        "sorts/bead_sort.zig",
        "sorts/cyclic_sort.zig",
        "sorts/exchange_sort.zig",
        "sorts/iterative_merge_sort.zig",
        "sorts/pigeon_sort.zig",
        "sorts/pigeonhole_sort.zig",
        "sorts/quick_sort_3_partition.zig",
        "sorts/recursive_quick_sort.zig",
        "sorts/shrink_shell_sort.zig",
        "sorts/stalin_sort.zig",
        "sorts/bitonic_sort.zig",
        "sorts/circle_sort.zig",
        "sorts/dutch_national_flag_sort.zig",
        "sorts/odd_even_transposition_single_threaded.zig",
        "sorts/recursive_mergesort_array.zig",
        "sorts/slowsort.zig",
        "sorts/strand_sort.zig",
        "sorts/tree_sort.zig",
        "sorts/unknown_sort.zig",
        "sorts/merge_insertion_sort.zig",
        "sorts/external_sort.zig",
        "sorts/intro_sort.zig",
        "sorts/msd_radix_sort.zig",
        "sorts/natural_sort.zig",
        "sorts/odd_even_transposition_parallel.zig",
        "sorts/patience_sort.zig",
        "sorts/tim_sort.zig",
        "sorts/topological_sort.zig",
        // Searches
        "searches/linear_search.zig",
        "searches/binary_search.zig",
        "searches/exponential_search.zig",
        "searches/interpolation_search.zig",
        "searches/jump_search.zig",
        "searches/ternary_search.zig",
        // Maths
        "maths/gcd.zig",
        "maths/lcm.zig",
        "maths/fibonacci.zig",
        "maths/prime_check.zig",
        "maths/sieve_of_eratosthenes.zig",
        "maths/power.zig",
        "maths/factorial.zig",
        "maths/collatz_sequence.zig",
        "maths/extended_euclidean.zig",
        "maths/modular_inverse.zig",
        "maths/eulers_totient.zig",
        "maths/chinese_remainder_theorem.zig",
        "maths/binomial_coefficient.zig",
        "maths/integer_square_root.zig",
        "maths/miller_rabin.zig",
        "maths/matrix_exponentiation.zig",
        "maths/perfect_number.zig",
        "maths/aliquot_sum.zig",
        "maths/fermat_little_theorem.zig",
        "maths/segmented_sieve.zig",
        "maths/odd_sieve.zig",
        "maths/twin_prime.zig",
        "maths/lucas_series.zig",
        "maths/josephus_problem.zig",
        "maths/sum_of_digits.zig",
        "maths/number_of_digits.zig",
        "maths/is_int_palindrome.zig",
        "maths/perfect_square.zig",
        "maths/perfect_cube.zig",
        "maths/quadratic_equations_complex_numbers.zig",
        "maths/decimal_to_fraction.zig",
        "maths/armstrong_numbers.zig",
        "maths/automorphic_number.zig",
        "maths/catalan_number.zig",
        "maths/happy_number.zig",
        "maths/hexagonal_number.zig",
        "maths/pronic_number.zig",
        "maths/proth_number.zig",
        "maths/triangular_numbers.zig",
        "maths/hamming_numbers.zig",
        "maths/polygonal_numbers.zig",
        "maths/average_mean.zig",
        "maths/average_median.zig",
        "maths/average_mode.zig",
        "maths/find_max.zig",
        "maths/find_min.zig",
        "maths/factors.zig",
        "maths/geometric_mean.zig",
        "maths/line_length.zig",
        "maths/euclidean_distance.zig",
        "maths/manhattan_distance.zig",
        "maths/abs.zig",
        "maths/average_absolute_deviation.zig",
        "maths/chebyshev_distance.zig",
        "maths/minkowski_distance.zig",
        "maths/jaccard_similarity.zig",
        "maths/decimal_isolate.zig",
        "maths/floor.zig",
        "maths/ceil.zig",
        "maths/signum.zig",
        "maths/remove_digit.zig",
        "maths/addition_without_arithmetic.zig",
        "maths/arc_length.zig",
        "maths/check_polygon.zig",
        "maths/combinations.zig",
        "maths/double_factorial.zig",
        "maths/pythagoras.zig",
        "maths/sum_of_arithmetic_series.zig",
        "maths/sum_of_geometric_progression.zig",
        "maths/sum_of_harmonic_series.zig",
        "maths/sylvester_sequence.zig",
        "maths/two_sum.zig",
        "maths/two_pointer.zig",
        "maths/three_sum.zig",
        "maths/triplet_sum.zig",
        "maths/sumset.zig",
        "maths/max_sum_sliding_window.zig",
        "maths/sock_merchant.zig",
        "maths/polynomial_evaluation.zig",
        "maths/kth_lexicographic_permutation.zig",
        "maths/largest_of_very_large_numbers.zig",
        // Data Structures
        "data_structures/stack.zig",
        "data_structures/queue.zig",
        "data_structures/singly_linked_list.zig",
        "data_structures/doubly_linked_list.zig",
        "data_structures/binary_search_tree.zig",
        "data_structures/min_heap.zig",
        "data_structures/trie.zig",
        "data_structures/disjoint_set.zig",
        "data_structures/avl_tree.zig",
        "data_structures/max_heap.zig",
        "data_structures/priority_queue.zig",
        "data_structures/hash_map_open_addressing.zig",
        "data_structures/segment_tree.zig",
        "data_structures/fenwick_tree.zig",
        "data_structures/red_black_tree.zig",
        "data_structures/lru_cache.zig",
        "data_structures/deque.zig",
        // Dynamic Programming
        "dynamic_programming/climbing_stairs.zig",
        "dynamic_programming/fibonacci_dp.zig",
        "dynamic_programming/coin_change.zig",
        "dynamic_programming/max_subarray_sum.zig",
        "dynamic_programming/longest_common_subsequence.zig",
        "dynamic_programming/edit_distance.zig",
        "dynamic_programming/knapsack.zig",
        "dynamic_programming/longest_increasing_subsequence.zig",
        "dynamic_programming/rod_cutting.zig",
        "dynamic_programming/matrix_chain_multiplication.zig",
        "dynamic_programming/palindrome_partitioning.zig",
        "dynamic_programming/word_break.zig",
        "dynamic_programming/catalan_numbers.zig",
        "dynamic_programming/subset_sum.zig",
        "dynamic_programming/egg_drop_problem.zig",
        "dynamic_programming/longest_palindromic_subsequence.zig",
        "dynamic_programming/max_product_subarray.zig",
        // Graphs
        "graphs/bfs.zig",
        "graphs/dfs.zig",
        "graphs/dijkstra.zig",
        "graphs/bellman_ford.zig",
        "graphs/topological_sort.zig",
        "graphs/floyd_warshall.zig",
        "graphs/detect_cycle.zig",
        "graphs/connected_components.zig",
        "graphs/kruskal.zig",
        "graphs/prim.zig",
        "graphs/a_star_search.zig",
        "graphs/tarjan_scc.zig",
        "graphs/bridges.zig",
        "graphs/eulerian_path_circuit_undirected.zig",
        "graphs/ford_fulkerson.zig",
        "graphs/bipartite_check_bfs.zig",
        "graphs/articulation_points.zig",
        "graphs/kosaraju_scc.zig",
        "graphs/kahn_topological_sort.zig",
        "graphs/breadth_first_search_shortest_path.zig",
        "graphs/boruvka_mst.zig",
        "graphs/zero_one_bfs_shortest_path.zig",
        "graphs/bidirectional_breadth_first_search.zig",
        "graphs/dijkstra_binary_grid.zig",
        "graphs/even_tree.zig",
        "graphs/gale_shapley_stable_matching.zig",
        "graphs/page_rank.zig",
        "graphs/bidirectional_dijkstra.zig",
        "graphs/greedy_best_first.zig",
        "graphs/dinic_max_flow.zig",
        "graphs/bidirectional_search.zig",
        "graphs/minimum_path_sum.zig",
        "graphs/deep_clone_graph.zig",
        "graphs/dijkstra_matrix.zig",
        "graphs/breadth_first_search_2.zig",
        "graphs/depth_first_search_2.zig",
        "graphs/dijkstra_2.zig",
        "graphs/dijkstra_alternate.zig",
        "graphs/greedy_min_vertex_cover.zig",
        "graphs/matching_min_vertex_cover.zig",
        "graphs/karger_min_cut.zig",
        "graphs/random_graph_generator.zig",
        "graphs/markov_chain.zig",
        "graphs/kahn_longest_distance.zig",
        "graphs/graph_adjacency_list.zig",
        "graphs/graph_adjacency_matrix.zig",
        // Bit Manipulation
        "bit_manipulation/is_power_of_two.zig",
        "bit_manipulation/count_set_bits.zig",
        "bit_manipulation/find_unique_number.zig",
        "bit_manipulation/reverse_bits.zig",
        "bit_manipulation/missing_number.zig",
        "bit_manipulation/power_of_4.zig",
        // Conversions
        "conversions/decimal_to_binary.zig",
        "conversions/binary_to_decimal.zig",
        "conversions/decimal_to_hexadecimal.zig",
        "conversions/binary_to_hexadecimal.zig",
        "conversions/roman_to_integer.zig",
        "conversions/integer_to_roman.zig",
        "conversions/temperature_conversion.zig",
        // Ciphers
        "ciphers/caesar_cipher.zig",
        "ciphers/rot13.zig",
        "ciphers/atbash.zig",
        "ciphers/vigenere_cipher.zig",
        "ciphers/rail_fence_cipher.zig",
        "ciphers/xor_cipher.zig",
        "ciphers/base64_cipher.zig",
        "ciphers/transposition_cipher.zig",
        "ciphers/a1z26.zig",
        // Hashing
        "hashing/sha256.zig",
        // Greedy Methods
        "greedy_methods/best_time_to_buy_sell_stock.zig",
        "greedy_methods/minimum_coin_change.zig",
        "greedy_methods/minimum_waiting_time.zig",
        "greedy_methods/fractional_knapsack.zig",
        "greedy_methods/activity_selection.zig",
        "greedy_methods/huffman_coding.zig",
        "greedy_methods/job_sequencing_with_deadline.zig",
        // Matrix
        "matrix/pascal_triangle.zig",
        "matrix/matrix_multiply.zig",
        "matrix/matrix_transpose.zig",
        "matrix/rotate_matrix.zig",
        "matrix/spiral_print.zig",
        // Backtracking
        "backtracking/permutations.zig",
        "backtracking/combinations.zig",
        "backtracking/subsets.zig",
        "backtracking/generate_parentheses.zig",
        "backtracking/n_queens.zig",
        "backtracking/sudoku_solver.zig",
        // Strings
        "strings/palindrome.zig",
        "strings/reverse_words.zig",
        "strings/anagram.zig",
        "strings/hamming_distance.zig",
        "strings/naive_string_search.zig",
        "strings/knuth_morris_pratt.zig",
        "strings/rabin_karp.zig",
        "strings/z_function.zig",
        "strings/levenshtein_distance.zig",
        "strings/is_pangram.zig",
        "strings/aho_corasick.zig",
        "strings/suffix_array.zig",
        "strings/run_length_encoding.zig",
        "strings/camel_case_to_snake_case.zig",
        "strings/can_string_be_rearranged_as_palindrome.zig",
        "strings/capitalize.zig",
        "strings/count_vowels.zig",
        "strings/is_contains_unique_chars.zig",
        "strings/is_isogram.zig",
        "strings/join.zig",
        "strings/lower.zig",
        "strings/split.zig",
        "strings/upper.zig",
        "strings/alternative_string_arrange.zig",
        "strings/boyer_moore_search.zig",
        "strings/bitap_string_match.zig",
        "strings/prefix_function.zig",
        "strings/remove_duplicate.zig",
        "strings/reverse_letters.zig",
        "strings/snake_case_to_camel_pascal_case.zig",
        "strings/strip.zig",
        "strings/title.zig",
        "strings/word_occurrence.zig",
        "strings/pig_latin.zig",
        "strings/wildcard_pattern_matching.zig",
        "strings/top_k_frequent_words.zig",
        "strings/manacher.zig",
        "strings/min_cost_string_conversion.zig",
    };

    for (test_files) |file| {
        // Zig 0.15+ API：addTest 使用 root_module + createModule 模式
        const t = b.addTest(.{
            .root_module = b.createModule(.{
                .root_source_file = b.path(file),
                .target = target,
                .optimize = optimize,
            }),
        });
        const run = b.addRunArtifact(t);
        test_step.dependOn(&run.step);
    }
}
