//! Heap's Algorithm (Divide and Conquer) - Zig implementation
//! Reference: https://github.com/TheAlgorithms/Python/blob/master/divide_and_conquer/heaps_algorithm.py

const std = @import("std");
const testing = std.testing;

fn appendPermutation(
    allocator: std.mem.Allocator,
    results: *std.ArrayListUnmanaged([]i64),
    arr: []const i64,
) std.mem.Allocator.Error!void {
    const copy = try allocator.dupe(i64, arr);
    errdefer allocator.free(copy);
    try results.append(allocator, copy);
}

fn generate(
    allocator: std.mem.Allocator,
    k: usize,
    arr: []i64,
    results: *std.ArrayListUnmanaged([]i64),
) std.mem.Allocator.Error!void {
    if (k == 1) {
        try appendPermutation(allocator, results, arr);
        return;
    }

    try generate(allocator, k - 1, arr, results);

    var i: usize = 0;
    while (i < k - 1) : (i += 1) {
        if (k % 2 == 0) {
            std.mem.swap(i64, &arr[i], &arr[k - 1]);
        } else {
            std.mem.swap(i64, &arr[0], &arr[k - 1]);
        }
        try generate(allocator, k - 1, arr, results);
    }
}

/// Returns all permutations generated by recursive Heap's algorithm.
///
/// Time complexity: O(n * n!)
/// Space complexity: O(n * n!)
pub fn heaps(allocator: std.mem.Allocator, input: []const i64) std.mem.Allocator.Error![][]i64 {
    var results = std.ArrayListUnmanaged([]i64){};
    errdefer {
        for (results.items) |perm| allocator.free(perm);
        results.deinit(allocator);
    }

    if (input.len <= 1) {
        try appendPermutation(allocator, &results, input);
        return results.toOwnedSlice(allocator);
    }

    const working = try allocator.dupe(i64, input);
    defer allocator.free(working);

    try generate(allocator, working.len, working, &results);
    return results.toOwnedSlice(allocator);
}

pub fn freePermutations(allocator: std.mem.Allocator, permutations: [][]i64) void {
    for (permutations) |perm| allocator.free(perm);
    allocator.free(permutations);
}

test "heaps algorithm: python examples" {
    const alloc = testing.allocator;

    const p0 = try heaps(alloc, &[_]i64{});
    defer freePermutations(alloc, p0);
    try testing.expectEqual(@as(usize, 1), p0.len);
    try testing.expectEqual(@as(usize, 0), p0[0].len);

    const p1 = try heaps(alloc, &[_]i64{0});
    defer freePermutations(alloc, p1);
    try testing.expectEqual(@as(usize, 1), p1.len);
    try testing.expectEqualSlices(i64, &[_]i64{0}, p1[0]);

    const p2 = try heaps(alloc, &[_]i64{ -1, 1 });
    defer freePermutations(alloc, p2);
    try testing.expectEqual(@as(usize, 2), p2.len);
    try testing.expectEqualSlices(i64, &[_]i64{ -1, 1 }, p2[0]);
    try testing.expectEqualSlices(i64, &[_]i64{ 1, -1 }, p2[1]);

    const p3 = try heaps(alloc, &[_]i64{ 1, 2, 3 });
    defer freePermutations(alloc, p3);
    const expected = [_][]const i64{
        &[_]i64{ 1, 2, 3 },
        &[_]i64{ 2, 1, 3 },
        &[_]i64{ 3, 1, 2 },
        &[_]i64{ 1, 3, 2 },
        &[_]i64{ 2, 3, 1 },
        &[_]i64{ 3, 2, 1 },
    };
    try testing.expectEqual(expected.len, p3.len);
    for (expected, p3) |exp, got| {
        try testing.expectEqualSlices(i64, exp, got);
    }
}

test "heaps algorithm: extreme unique count for 4 elements" {
    const alloc = testing.allocator;

    const perms = try heaps(alloc, &[_]i64{ 1, 2, 3, 4 });
    defer freePermutations(alloc, perms);

    try testing.expectEqual(@as(usize, 24), perms.len);

    for (0..perms.len) |i| {
        for (i + 1..perms.len) |j| {
            try testing.expect(!std.mem.eql(i64, perms[i], perms[j]));
        }
    }
}
