//! Heap's Algorithm (Iterative) - Zig implementation
//! Reference: https://github.com/TheAlgorithms/Python/blob/master/divide_and_conquer/heaps_algorithm_iterative.py

const std = @import("std");
const testing = std.testing;

fn appendPermutation(
    allocator: std.mem.Allocator,
    results: *std.ArrayListUnmanaged([]i64),
    arr: []const i64,
) std.mem.Allocator.Error!void {
    const copy = try allocator.dupe(i64, arr);
    errdefer allocator.free(copy);
    try results.append(allocator, copy);
}

/// Returns all permutations generated by iterative Heap's algorithm.
///
/// Time complexity: O(n * n!)
/// Space complexity: O(n * n!)
pub fn heapsIterative(allocator: std.mem.Allocator, input: []const i64) std.mem.Allocator.Error![][]i64 {
    var results = std.ArrayListUnmanaged([]i64){};
    errdefer {
        for (results.items) |perm| allocator.free(perm);
        results.deinit(allocator);
    }

    if (input.len <= 1) {
        try appendPermutation(allocator, &results, input);
        return results.toOwnedSlice(allocator);
    }

    const arr = try allocator.dupe(i64, input);
    defer allocator.free(arr);

    const c = try allocator.alloc(usize, arr.len);
    defer allocator.free(c);
    @memset(c, 0);

    try appendPermutation(allocator, &results, arr);

    var i: usize = 0;
    while (i < arr.len) {
        if (c[i] < i) {
            if (i % 2 == 0) {
                std.mem.swap(i64, &arr[0], &arr[i]);
            } else {
                std.mem.swap(i64, &arr[c[i]], &arr[i]);
            }

            try appendPermutation(allocator, &results, arr);
            c[i] += 1;
            i = 0;
        } else {
            c[i] = 0;
            i += 1;
        }
    }

    return results.toOwnedSlice(allocator);
}

pub fn freePermutations(allocator: std.mem.Allocator, permutations: [][]i64) void {
    for (permutations) |perm| allocator.free(perm);
    allocator.free(permutations);
}

test "heaps algorithm iterative: python examples" {
    const alloc = testing.allocator;

    const p0 = try heapsIterative(alloc, &[_]i64{});
    defer freePermutations(alloc, p0);
    try testing.expectEqual(@as(usize, 1), p0.len);
    try testing.expectEqual(@as(usize, 0), p0[0].len);

    const p1 = try heapsIterative(alloc, &[_]i64{0});
    defer freePermutations(alloc, p1);
    try testing.expectEqual(@as(usize, 1), p1.len);
    try testing.expectEqualSlices(i64, &[_]i64{0}, p1[0]);

    const p2 = try heapsIterative(alloc, &[_]i64{ -1, 1 });
    defer freePermutations(alloc, p2);
    try testing.expectEqual(@as(usize, 2), p2.len);
    try testing.expectEqualSlices(i64, &[_]i64{ -1, 1 }, p2[0]);
    try testing.expectEqualSlices(i64, &[_]i64{ 1, -1 }, p2[1]);

    const p3 = try heapsIterative(alloc, &[_]i64{ 1, 2, 3 });
    defer freePermutations(alloc, p3);
    const expected = [_][]const i64{
        &[_]i64{ 1, 2, 3 },
        &[_]i64{ 2, 1, 3 },
        &[_]i64{ 3, 1, 2 },
        &[_]i64{ 1, 3, 2 },
        &[_]i64{ 2, 3, 1 },
        &[_]i64{ 3, 2, 1 },
    };
    try testing.expectEqual(expected.len, p3.len);
    for (expected, p3) |exp, got| {
        try testing.expectEqualSlices(i64, exp, got);
    }
}

test "heaps algorithm iterative: extreme unique count for 4 elements" {
    const alloc = testing.allocator;

    const perms = try heapsIterative(alloc, &[_]i64{ 1, 2, 3, 4 });
    defer freePermutations(alloc, perms);

    try testing.expectEqual(@as(usize, 24), perms.len);
    for (0..perms.len) |i| {
        for (i + 1..perms.len) |j| {
            try testing.expect(!std.mem.eql(i64, perms[i], perms[j]));
        }
    }
}
