//! Project Euler Problem 51: Prime Digit Replacements - Zig implementation
//! Reference: https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_051/sol1.py

const std = @import("std");
const testing = std.testing;

pub const Problem051Error = error{InvalidFamilyLength};

const limit = 1_000_000;

const PrimeData = struct {
    primes: []u32,
    is_candidate_prime: []bool,
};

fn freePrimeData(allocator: std.mem.Allocator, data: PrimeData) void {
    allocator.free(data.primes);
    allocator.free(data.is_candidate_prime);
}

fn countDigits(number: u32) [10]u8 {
    var counts = [_]u8{0} ** 10;
    var current = number;
    if (current == 0) {
        counts[0] = 1;
        return counts;
    }
    while (current > 0) : (current /= 10) {
        counts[current % 10] += 1;
    }
    return counts;
}

fn repeatedDigitTotal(number: u32) u8 {
    const counts = countDigits(number);
    var total: u8 = 0;
    for (counts) |count| {
        if (count > 1) total += count - 1;
    }
    return total;
}

fn replacementFamily(number: u32, digit_to_replace: u8) [10]u32 {
    var buffer: [16]u8 = undefined;
    const source = std.fmt.bufPrint(&buffer, "{d}", .{number}) catch unreachable;
    var family: [10]u32 = undefined;

    for (0..10) |replacement| {
        var value: u32 = 0;
        for (source) |char| {
            const digit = if (char == digit_to_replace + '0') @as(u8, @intCast(replacement)) else char - '0';
            value = value * 10 + digit;
        }
        family[replacement] = value;
    }
    return family;
}

fn repeatedDigits(number: u32, out: *[10]u8) usize {
    const counts = countDigits(number);
    var len: usize = 0;
    for (0..10) |digit| {
        if (counts[digit] >= 2) {
            out[len] = @intCast(digit);
            len += 1;
        }
    }
    return len;
}

fn buildPrimeData(allocator: std.mem.Allocator) !PrimeData {
    const is_prime = try allocator.alloc(bool, limit);
    defer allocator.free(is_prime);
    @memset(is_prime, true);
    is_prime[0] = false;
    is_prime[1] = false;

    var i: usize = 2;
    while (i * i < limit) : (i += 1) {
        if (!is_prime[i]) continue;
        var multiple = i * i;
        while (multiple < limit) : (multiple += i) {
            is_prime[multiple] = false;
        }
    }

    const is_candidate_prime = try allocator.alloc(bool, limit);
    @memset(is_candidate_prime, false);

    var primes = std.ArrayListUnmanaged(u32){};
    errdefer primes.deinit(allocator);
    for (0..limit) |n| {
        if (!is_prime[n]) continue;
        if (repeatedDigitTotal(@intCast(n)) < 3) continue;
        try primes.append(allocator, @intCast(n));
        is_candidate_prime[n] = true;
    }

    return .{
        .primes = try primes.toOwnedSlice(allocator),
        .is_candidate_prime = is_candidate_prime,
    };
}

/// Returns the replacement families generated by replacing each repeated digit
/// with every digit from 0 through 9.
/// Caller owns the returned matrix.
///
/// Time complexity: O(r * d * 10)
/// Space complexity: O(r * 10)
pub fn digitReplacements(allocator: std.mem.Allocator, number: u32) ![][]u32 {
    var digits: [10]u8 = undefined;
    const digits_len = repeatedDigits(number, &digits);

    const families = try allocator.alloc([]u32, digits_len);
    errdefer allocator.free(families);

    var built: usize = 0;
    errdefer {
        for (families[0..built]) |family| allocator.free(family);
    }

    for (digits[0..digits_len], 0..) |digit, idx| {
        const family = replacementFamily(number, digit);
        families[idx] = try allocator.alloc(u32, family.len);
        @memcpy(families[idx], &family);
        built += 1;
    }

    return families;
}

pub fn freeFamilies(allocator: std.mem.Allocator, families: [][]u32) void {
    for (families) |family| allocator.free(family);
    allocator.free(families);
}

/// Returns the smallest prime in the desired family.
///
/// Note: for family sizes other than the Euler target `8`, the Python reference
/// implementation depends on hash-set iteration order. This Zig port scans the
/// candidate primes in ascending order deterministically.
///
/// Time complexity: dominated by the sieve plus the family scan, roughly O(limit log log limit)
/// Space complexity: O(limit)
pub fn solution(allocator: std.mem.Allocator, family_length: usize) (Problem051Error || std.mem.Allocator.Error)!i32 {
    if (family_length == 0) return error.InvalidFamilyLength;

    const prime_data = try buildPrimeData(allocator);
    defer freePrimeData(allocator, prime_data);

    const numbers_checked = try allocator.alloc(bool, limit);
    defer allocator.free(numbers_checked);
    @memset(numbers_checked, false);

    for (prime_data.primes) |prime| {
        if (numbers_checked[prime]) continue;

        const families = try digitReplacements(allocator, prime);
        defer freeFamilies(allocator, families);

        for (families) |family| {
            var count: usize = 0;
            var smallest: u32 = std.math.maxInt(u32);
            for (family) |member| {
                if (member < limit) numbers_checked[member] = true;
                if (member < limit and prime_data.is_candidate_prime[member]) {
                    count += 1;
                    if (member < smallest) smallest = member;
                }
            }
            if (count == family_length) return @intCast(smallest);
        }
    }

    return -1;
}

test "problem 051: python reference" {
    const allocator = testing.allocator;
    try testing.expectEqual(@as(i32, 121_313), try solution(allocator, 8));
}

test "problem 051: helper semantics and extremes" {
    const allocator = testing.allocator;

    const replacements_544 = try digitReplacements(allocator, 544);
    defer freeFamilies(allocator, replacements_544);
    try testing.expectEqual(@as(usize, 1), replacements_544.len);
    try testing.expectEqualSlices(u32, &[_]u32{ 500, 511, 522, 533, 544, 555, 566, 577, 588, 599 }, replacements_544[0]);

    const replacements_3112 = try digitReplacements(allocator, 3112);
    defer freeFamilies(allocator, replacements_3112);
    try testing.expectEqual(@as(usize, 1), replacements_3112.len);
    try testing.expectEqualSlices(u32, &[_]u32{ 3002, 3112, 3222, 3332, 3442, 3552, 3662, 3772, 3882, 3992 }, replacements_3112[0]);

    try testing.expectEqual(@as(i32, 11311), try solution(allocator, 2));
    try testing.expectEqual(@as(i32, 11113), try solution(allocator, 3));
    try testing.expectError(error.InvalidFamilyLength, solution(allocator, 0));
}
